apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service  # Sets Deployment name
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: db-service
          image: dev0zklabs/atlas-demo-microservice:python-frontend-service
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db-service # Sets service name
  namespace: atlas
  labels:
    app: db-service # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432 # Sets port to run the db-service application
  selector:
    app: db-service