apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-service
  name: java-service
  namespace: atlas
spec:
  ports:
  - port: 30001
    protocol: TCP
    targetPort: 30001
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30001
  selector:
    app: java-service
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-service
  name: java-service
  namespace: atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service
  strategy: {}
  template:
    metadata:
      labels:
        app: java-service
    spec:
      containers:
      - args:
        - java-service
        image: dev0zklabs/atlas-demo-microservice:java-service
        name: java-service
        ports:
        - containerPort: 30001
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: envs-config
        resources: {}
status: {}
